(function() {var implementors = {};
implementors['portaudio'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='portaudio/stream/enum.StreamCallbackResult.html' title='portaudio::stream::StreamCallbackResult'>StreamCallbackResult</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamTimeInfo.html' title='portaudio::stream::StreamTimeInfo'>StreamTimeInfo</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamCallbackFlags.html' title='portaudio::stream::StreamCallbackFlags'>StreamCallbackFlags</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamFlags.html' title='portaudio::stream::StreamFlags'>StreamFlags</a>","impl&lt;T: <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamParameters.html' title='portaudio::stream::StreamParameters'>StreamParameters</a>&lt;T&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='portaudio/stream/struct.StreamInfo.html' title='portaudio::stream::StreamInfo'>StreamInfo</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='portaudio/enum.PaError.html' title='portaudio::PaError'>PaError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='portaudio/hostapi/enum.HostApiType.html' title='portaudio::hostapi::HostApiType'>HostApiType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
