(function() {var implementors = {};
implementors["portaudio_rs"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"portaudio_rs/stream/enum.StreamCallbackResult.html\" title=\"enum portaudio_rs::stream::StreamCallbackResult\">StreamCallbackResult</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"portaudio_rs/stream/struct.StreamTimeInfo.html\" title=\"struct portaudio_rs::stream::StreamTimeInfo\">StreamTimeInfo</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"portaudio_rs/stream/struct.StreamCallbackFlags.html\" title=\"struct portaudio_rs::stream::StreamCallbackFlags\">StreamCallbackFlags</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"portaudio_rs/stream/struct.StreamFlags.html\" title=\"struct portaudio_rs::stream::StreamFlags\">StreamFlags</a>","impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"portaudio_rs/stream/struct.StreamParameters.html\" title=\"struct portaudio_rs::stream::StreamParameters\">StreamParameters</a>&lt;T&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"portaudio_rs/stream/struct.StreamInfo.html\" title=\"struct portaudio_rs::stream::StreamInfo\">StreamInfo</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"portaudio_rs/enum.PaError.html\" title=\"enum portaudio_rs::PaError\">PaError</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"portaudio_rs/hostapi/enum.HostApiType.html\" title=\"enum portaudio_rs::hostapi::HostApiType\">HostApiType</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
